# Default values for tlv.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

appName: tlv

global:
  dockerRepository: nexus-docker-private-group.ossim.io

  createIngress: true
  useTls: false
  useTLSClientAuth: false
  sslCertSecretName: null
  authSslCertSecretName: null

  createImagePullSecret: true
  useImagePullSecret: true

resources:
  limits:
    cpu: 1200m
    memory: 1000Mi
  requests:
    cpu: 35m
    memory: 500Mi
    
image:
  name: tlv
  pullPolicy: Always

ingressPath: /tlv
internalPort: 8080
externalPort: 8080

livenessProbe:
  failureThreshold: 5
  initialDelaySeconds: 30
  periodSeconds: 15
  successThreshold: 1
  timeoutSeconds: 3

readinessProbe:
  failureThreshold: 15
  initialDelaySeconds: 30
  periodSeconds: 15
  successThreshold: 1
  timeoutSeconds: 3
  path: /tlv/actuator/health

terminationGracePeriodSeconds: 30
