{{- if (pluck "createImagePullSecret" .Values .Values.global | first) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.fullnameOverride }}-pull-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ include "tlv.imagePullSecret" . }}
{{- end }}