version: '3'

services:
    tlv:
        image: openjdk:8-alpine
        ports:
            - 8080:8080
        volumes:
            - "./config.yml:/home/config.yml"
            - "./build/libs/tlv-app-${buildVersion:-1.6.1}-SNAPSHOT.jar:/home/tlv.jar"
        depends_on:
            - postgis
        command: java -jar /home/tlv.jar --spring.config.location=/home/config.yml

    postgis:
        image: mdillon/postgis:latest
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: tlv
