//==================================================================================================
// This is the Jenkins pipeline script for building the TLV application.
// Environment varialbes that MUST be passed in by Jenkins:
//    BUILD_NODE: The dynamic machine to build the application on.
//    OSSIM_GIT_BRANCH: The tag of the branch to be built. Typically dev or master.
//    
// Environment varaibles that MUST be set in the Jenkins global environment (manage jenkins -> configure system -> environment varaibles)
//    REPOSITORY_MANAGER_USER: The user to use when pushing artifacts
//    REPOSITORY_MANAGER_PASSWORD: The password to use when pushing artifacts
//    DOCKER_REGISTRY_USERNAME: The user to use logging into the docker registry
//    DOCKER_REGISTRY_PASSWORD: The password to use logging into the docker registry
//==================================================================================================

def notifyObj
node("${BUILD_NODE}"){

    stage("Load Variables"){
        dir("ossim-ci"){
            git branch: "${OSSIM_GIT_BRANCH}",
            url: "${GIT_PRIVATE_SERVER_URL}/ossim-ci.git"
            credentialsId: ${CREDENTIALS_ID}"
        }

        dir("tlv"){
            git branch: "${OSSIM_GIT_BRANCH}", 
            url: "${GIT_PUBLIC_SERVER_URL}/tlv.git",
            credentialsId: "${CREDENTIALS_ID}"
        }

        load "ossim-ci/jenkins/variables/pipeline-variables-common.groovy"
        load "tlv/scripts/pipeline-variables-tlv.groovy"
    }

    stage("Checkout"){
        dir(appName) {
            git branch: "${OSSIM_GIT_BRANCH}", 
            url: "${GIT_PUBLIC_SERVER_URL}/${appName}.git",
            credentialsId: "${CREDENTIALS_ID}"
        }

        dir(omarCommonProjName) {
            git branch: "${OSSIM_GIT_BRANCH}", 
            url: "${GIT_PUBLIC_SERVER_URL}/${omarCommonProjName}.git",
            credentialsId: "${CREDENTIALS_ID}"
        }
    }

    stage("Download Artifacts") {
        step ([$class: "CopyArtifact",
               projectName: "ossim-ci-${OSSIM_GIT_BRANCH}",
               filter: "ossim-ci-${OSSIM_GIT_BRANCH}.tgz",
               flatten: true])
        sh "tar xvfz ossim-ci-${OSSIM_GIT_BRANCH}.tgz"
        notifyObj = load "${env.WORKSPACE}/ossim-ci/jenkins/pipeline/notify.groovy"
    }

    try {
      stage ("Publish App Nexus")
      {
          withCredentials([[$class: 'UsernamePasswordMultiBinding',
                            credentialsId: 'nexusCredentials',
                            usernameVariable: 'REPOSITORY_MANAGER_USER',
                            passwordVariable: 'REPOSITORY_MANAGER_PASSWORD']])
            {
              sh """
              pushd ${workspaceDir}/${appName}
              gradle :${appName}-app:upload
              popd
              """
            }
      }

      stage ("Publish Docker App")
      {
        withCredentials([[$class: 'UsernamePasswordMultiBinding',
                        credentialsId: 'dockerCredentials',
                        usernameVariable: 'DOCKER_REGISTRY_USERNAME',
                        passwordVariable: 'DOCKER_REGISTRY_PASSWORD']])
        {
            // Run all tasks on the app. This includes pushing to OpenShift and S3.
            sh """
            pushd ${workspaceDir}/${appName}
            gradle :${appName}-app:${GRADLE_TASK}
            popd
            """
        }
      }
    }
    catch(e){
        echo e.toString()
        currentBuild.result = "FAILED"
        notifyObj?.notifyFailed()
    }
    try {
        stage('SonarQube Analysis') {
            withSonarQubeEnv("${SONARQUBE_NAME}") {
                // requires SonarQube Scanner for Gradle 2.1+
                // It's important to add --info because of SONARJNKNS-281
                sh """
                  pushd ${workspaceDir}/${appName}
                  gradle --info :${appName}-app:sonarqube -Dsonar.projectKey=${appName}
                  popd
                """
            }
        }
    }
    catch (e) {
        echo e.toString()
    }
    try {
        stage('HPFortify Analysis') {
            // Commented out S3 publish stage: 
            // aws s3 cp fortifyResults-${appName}.pdf s3://o2-private/hpfortify/fortify-reports-pdf/
            // aws s3 cp fortifyResults-${appName}.fpr s3://o2-private/hpfortify/fortify-reports-fpr/
                 
            dir(appName) {
              sh """
                 export PATH=${PATH}:/opt/HPE_Security/Fortify_SCA_and_Apps_17.20/bin
                 sourceanalyzer -64 -b ${appName} -clean
                 sourceanalyzer -64 -b ${appName} ${workspaceDir}/${appName}/apps/${appName}-app/grails-app/assets/javascripts/menus/*.js
                 sourceanalyzer -64 -b ${appName} -scan -Xmx8G -f fortifyResults-${appName}-app.fpr
                 ReportGenerator -format pdf -f fortifyResults-${appName}.pdf -source fortifyResults-${appName}-app.fpr
                 fortifyclient -url ${HP_FORTIFY_URL} -authtoken ${HP_FORTIFY_TOKEN} uploadFPR -file fortifyResults-${appName}-app.fpr -applicationVersionID 2
                 """
            }
        }
   }
   catch (e) {
      echo e.toString()
   }
  stage("Clean Workspace")
   {
      if ("${CLEAN_WORKSPACE}" == "true")
        step([$class: 'WsCleanup'])
   }
}
